# Generated by Django 5.0.2 on 2025-05-24 16:29

from django.db import migrations

def create_initial_colleges_and_programs(apps, schema_editor):
    College = apps.get_model('alumni_id', 'College')
    Program = apps.get_model('alumni_id', 'Program')

    # Create Colleges
    coea = College.objects.create(code='COEA', name='College of Engineering and Architecture')
    ccs = College.objects.create(code='CCS', name='College of Computer Studies')
    cbe = College.objects.create(code='CBE', name='College of Business Education')
    coa = College.objects.create(code='COA', name='College of Arts')

    # Create Programs for College of Engineering and Architecture
    Program.objects.create(code='ARCH', name='Architecture', college=coea)
    Program.objects.create(code='CHE', name='Chemical Engineering', college=coea)
    Program.objects.create(code='CE', name='Civil Engineering', college=coea)
    Program.objects.create(code='CPE', name='Computer Engineering', college=coea)
    Program.objects.create(code='EE', name='Electrical Engineering', college=coea)
    Program.objects.create(code='ECE', name='Electronics Engineering', college=coea)
    Program.objects.create(code='IE', name='Industrial Engineering', college=coea)
    Program.objects.create(code='ME', name='Mechanical Engineering', college=coea)

    # Create Programs for College of Computer Studies
    Program.objects.create(code='CS', name='Computer Science', college=ccs)
    Program.objects.create(code='DSA', name='Data Science and Analytics', college=ccs)
    Program.objects.create(code='EMC', name='Entertainment and Multimedia Computing', college=ccs)
    Program.objects.create(code='IT', name='Information Technology', college=ccs)

    # Create Programs for College of Business Education
    Program.objects.create(code='ACC', name='Accountancy', college=cbe)
    Program.objects.create(code='AIS', name='Accounting Information System', college=cbe)
    Program.objects.create(code='BA', name='Business Administration', college=cbe)
    Program.objects.create(code='FM', name='Financial Management', college=cbe)
    Program.objects.create(code='HRM', name='Human Resource Management', college=cbe)
    Program.objects.create(code='LSCM', name='Logistics and Supply Chain Management', college=cbe)
    Program.objects.create(code='MM', name='Marketing Management', college=cbe)

    # Create Programs for College of Arts
    Program.objects.create(code='BAEL', name='Bachelor of Arts in English Language', college=coa)
    Program.objects.create(code='BAPS', name='Bachelor of Arts in Political Science', college=coa)

def remove_colleges_and_programs(apps, schema_editor):
    College = apps.get_model('alumni_id', 'College')
    College.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ('alumni_id', '0002_college_alumniprofile_college_program_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_colleges_and_programs, remove_colleges_and_programs),
    ]
